language: python
sudo: false
python:
- '2.7'
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a
# don't think we need all these packages, but copying from urbansim
- >
  conda create -q -c synthicity -n test-environment
  python=$TRAVIS_PYTHON_VERSION
  cytoolz ipython-notebook jinja2 matplotlib numpy pandas patsy pip scipy
  statsmodels pytables pytest pyyaml
- source activate test-environment
- pip install -r requirements.txt
script:
- pep8 baus
- py.test