# scenarios for hazards models
slr_scenarios:
      enable_in: ["1", "2", "5", "11", "12", "15", "20", "21", "22", "23", "24"]
      horizon_scenarios: ["1", "2", "5", "11", "12", "15"]
      draft_blueprint_scenarios: ["20", "21", "22", "23", "24"] # final blueprint is the same
      # progression
      rtff_prog: ["2", "7", "12"]
      cag_prog: ["1", "6", "11"]
      bttf_prog: ["5", "10", "15"]
      d_b_prog: ["20", "21", "22", "23", "24"] # final blueprint is the same
      # inundation
      mitigation_full: ["11", "15"] # futures round 2
      mitigation_partial: ["12"] # futures round 2
      d_bb_mitigation: ["21"]
      d_bp_mitigation: ["22", "23", "24"] # final blueprint is the same
eq_scenarios:
      enable_in: ["1", "2", "5", "11", "12", "15"]
      # scenarios for futures rounds 2 mitigation
      # rtff is not mitigated
      mitigation: ["11", "15"]