name: networks

desc: Neighborhood Accessibility Variables

model_type: networks

node_col: node_id

variable_definitions:
    
  - name: sum_residential_units
    dataframe: buildings
    varname: residential_units
    radius: 1500
    apply: np.log1p

  - name: sum_nonresidential_units
    dataframe: buildings
    varname: job_spaces
    radius: 1500
    apply: np.log1p

  - name: ave_sqft_per_unit
    dataframe: buildings
    varname: sqft_per_unit
    filters:
    - general_type == "Residential"
    radius: 1500
    apply: np.log1p
    decay: flat
    aggregation: average

  - name: ave_lot_size_per_unit
    dataframe: buildings
    varname: lot_size_per_unit
    filters:
    - general_type == "Residential"
    radius: 1500
    apply: np.log1p
    decay: flat
    aggregation: average

  - name: population
    dataframe: households
    varname: persons
    radius: 1500
    apply: np.log1p

  - name: poor
    dataframe: households
    filters:
    - income < 40000
    varname: persons
    radius: 1500
    apply: np.log1p

  - name: renters
    dataframe: households
    filters:
    - tenure == 2
    radius: 1500
    apply: np.log1p

  - name: sfdu
    dataframe: buildings
    filters:
    - building_type_id == 1
    radius: 1500
    apply: np.log1p

  - name: ave_hhsize
    dataframe: households
    varname: persons
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p

  - name: jobs
    dataframe: jobs
    radius: 1500
    apply: np.log1p

  - name: ave_income
    dataframe: households
    varname: income
    radius: 1500
    aggregation: average
    decay: flat
    apply: np.log1p
