aggregation_tables:
  - nodes
  - tmnodes
  - logsums


profit_vs_return_on_cost_combination_factor: 0.5


dont_build_most_dense_building: True


set_nan_price_to_zero: True


remove_invalid_building_ids: True


reconcile_residential_units_and_households: True


reconcile_non_residential_sqft_and_jobs: True


set_nan_price_to_zero: True


parcel_size_factor: 10.764


# this is really because we don't have limits right now for retail
eliminate_retail_zoning_from_juris:
  - 'Sonoma County'
  - 'Contra Costa County'
  - 'San Mateo County'
  - 'Solano County'
  - 'Napa County'
  - 'Marin County'
  - 'Benicia'
  - 'Brentwood'
  - 'Antioch'
  - 'Atherton'
  - 'Fairfax'
  - 'Hillsborough'
  - 'Belvedere'
  - 'Yountville'
  - 'Woodside'
  - 'Monte Sereno'
  - 'Los Altos Hills'
  - 'Half Moon Bay'
  - 'Larkspur'
  - 'Portola Valley'
  - 'Saratoga'
  - 'Cloverdale'
  - 'Livermore'
  - 'Los Gatos'
  - 'Tiburon'
  - 'Piedmont'
  - 'Ross'
  - 'Atherton'
  - 'Belmont'
  - 'Clayton'


clip_sqft_per_unit_based_on_dua:
  - threshold: 50
    max: 1000
  - threshold: 100
    max: 900
  - threshold: 150
    max: 800

ave_sqft_per_unit_clip:
  lower: 800
  upper: 2500


inclusionary_housing_settings:
  default:
    - type: jurisdictions
      amount: .2
      values:
        San Francisco:
  "1":
    - type: jurisdictions
      description: low setting
      amount: .05
      values:
      - Alameda
      - Alameda County
      - Albany
      - Atherton
      - Belmont
      - Belvedere
      - Berkeley
      - Burlingame
      - Campbell
      - Cloverdale
      - Concord
      - Contra Costa County
      - Corte Madera
      - Cupertino
      - Danville
      - Dublin
      - East Palo Alto
      - El Cerrito
      - Emeryville
      - Fairfax
      - Foster City
      - Fremont
      - Lafayette
      - Larkspur
      - Los Altos
      - Los Altos Hills
      - Los Gatos
      - Menlo Park
      - Millbrae
      - Milpitas
      - Monte Sereno
      - Moraga
      - Mountain View
      - Orinda
      - Palo Alto
      - Piedmont
      - Pleasanton
      - Redwood City
      - Ross
      - San Anselmo
      - San Bruno
      - San Carlos
      - San Francisco
      - San Jose
      - San Mateo
      - San Mateo County
      - San Ramon
      - Santa Clara
      - Santa Rosa
      - Saratoga
      - Sausalito
      - Sunnyvale
      - Tiburon
      - Union City
      - Walnut Creek
  "2":
    - type: jurisdictions
      description: medium setting
      amount: .1
      values:
      - Alameda
      - Alameda County
      - Albany
      - American Canyon
      - Antioch
      - Belmont
      - Benicia
      - Berkeley
      - Brisbane
      - Burlingame
      - Campbell
      - Cloverdale
      - Colma
      - Concord
      - Contra Costa County
      - Cotati
      - Cupertino
      - Daly City
      - Danville
      - Dixon
      - Dublin
      - East Palo Alto
      - El Cerrito
      - Emeryville
      - Fairfield
      - Fremont
      - Gilroy
      - Hayward
      - Hercules
      - Lafayette
      - Livermore
      - Los Altos
      - Martinez
      - Menlo Park
      - Millbrae
      - Milpitas
      - Moraga
      - Morgan Hill
      - Mountain View
      - Napa
      - Newark
      - Oakland
      - Oakley
      - Orinda
      - Palo Alto
      - Petaluma
      - Pinole
      - Pittsburg
      - Pleasant Hill
      - Pleasanton
      - Redwood City
      - Richmond
      - Rohnert Park
      - San Bruno
      - San Carlos
      - San Francisco
      - San Jose
      - San Leandro
      - San Mateo
      - San Mateo County
      - San Pablo
      - San Rafael
      - San Ramon
      - Santa Clara
      - Santa Rosa
      - Sebastopol
      - South San Francisco
      - Suisun City
      - Sunnyvale
      - Union City
      - Vacaville
      - Vallejo
      - Walnut Creek
      - Windsor  
  "3":
    - type: jurisdictions
      description: high setting
      amount: .2
      values:
      - San Jose
      - Oakland
      - San Francisco
  "4":
    - type: jurisdictions
      description: medium setting
      amount: .1
      values:
      - Alameda
      - Alameda County
      - Albany
      - American Canyon
      - Antioch
      - Belmont
      - Benicia
      - Berkeley
      - Brisbane
      - Burlingame
      - Campbell
      - Cloverdale
      - Colma
      - Concord
      - Contra Costa County
      - Cotati
      - Cupertino
      - Daly City
      - Danville
      - Dixon
      - Dublin
      - East Palo Alto
      - El Cerrito
      - Emeryville
      - Fairfield
      - Fremont
      - Gilroy
      - Hayward
      - Hercules
      - Lafayette
      - Livermore
      - Los Altos
      - Martinez
      - Menlo Park
      - Millbrae
      - Milpitas
      - Moraga
      - Morgan Hill
      - Mountain View
      - Napa
      - Newark
      - Oakland
      - Oakley
      - Orinda
      - Palo Alto
      - Petaluma
      - Pinole
      - Pittsburg
      - Pleasant Hill
      - Pleasanton
      - Redwood City
      - Richmond
      - Rohnert Park
      - San Bruno
      - San Carlos
      - San Francisco
      - San Jose
      - San Leandro
      - San Mateo
      - San Mateo County
      - San Pablo
      - San Rafael
      - San Ramon
      - Santa Clara
      - Santa Rosa
      - Sebastopol
      - South San Francisco
      - Suisun City
      - Sunnyvale
      - Union City
      - Vacaville
      - Vallejo
      - Walnut Creek
      - Windsor
  "5":
    - type: jurisdictions
      description: higher setting
      amount: .2
      values:
      - Alameda
      - Alameda County
      - Albany
      - American Canyon
      - Antioch
      - Atherton
      - Belmont
      - Belvedere
      - Benicia
      - Berkeley
      - Brisbane
      - Burlingame
      - Campbell
      - Cloverdale
      - Colma
      - Concord
      - Contra Costa County
      - Corte Madera
      - Cotati
      - Cupertino
      - Daly City
      - Danville
      - Dixon
      - Dublin
      - East Palo Alto
      - El Cerrito
      - Emeryville
      - Fairfield
      - Fremont
      - Gilroy
      - Hayward
      - Hercules
      - Hillsborough
      - Lafayette
      - Larkspur
      - Livermore
      - Los Altos
      - Los Gatos
      - Martinez
      - Menlo Park
      - Millbrae
      - Milpitas
      - Moraga
      - Morgan Hill
      - Mountain View
      - Napa
      - Newark
      - Novato
      - Oakland
      - Oakley
      - Orinda
      - Pacifica
      - Palo Alto
      - Petaluma
      - Piedmont
      - Pinole
      - Pittsburg
      - Pleasant Hill
      - Pleasanton
      - Redwood City
      - Richmond
      - Rohnert Park
      - San Bruno
      - San Carlos
      - San Francisco
      - San Jose
      - San Leandro
      - San Mateo
      - San Mateo County
      - San Pablo
      - San Rafael
      - San Ramon
      - Santa Clara
      - Santa Rosa
      - Sausalito 
      - Sebastopol
      - South San Francisco
      - Suisun City
      - Sunnyvale
      - Union City
      - Vacaville
      - Vallejo
      - Walnut Creek
      - Windsor

acct_settings:
  disable: False

  lump_sum_accounts:

    obag_settings:
      name: "OBAG"
      sending_buildings_subaccount_def: regional
      total_amount: 40000000
      receiving_buildings_filter: pda_id > 0
      subsidize_affordable: False
      enable_in_scenarios: ["1", "2", "3", "4", "5"]

    san_mateo_bond_settings:
      name: "San Mateo Affordable Housing Bond"
      sending_buildings_subaccount_def: regional
      total_amount: 40000000
      receiving_buildings_filter: county == 'San Mateo'
      subsidize_affordable: True
      enable_in_scenarios: []

    alameda_bond_settings:
      name: "Alameda Affordable Housing Bond"
      sending_buildings_subaccount_def: regional
      total_amount: 20000000
      receiving_buildings_filter: county == 'Alameda'
      subsidize_affordable: True
      enable_in_scenarios: []

    santa_clara_bond_settings:
      name: "Santa Clara Affordable Housing Bond"
      sending_buildings_subaccount_def: regional
      total_amount: 31000000
      receiving_buildings_filter: county == 'Santa Clara'
      subsidize_affordable: True
      enable_in_scenarios: []

    santa_francisco_bond_settings:
      name: "San Francisco Affordable Housing Bond"
      sending_buildings_subaccount_def: regional
      total_amount: 19000000
      receiving_buildings_filter: county == 'San Francisco'
      subsidize_affordable: True
      enable_in_scenarios: []

    parcel_tax_settings:
      name: "Parcel Tax"
      sending_buildings_subaccount_def: regional
      total_amount: 500000000
      receiving_buildings_filter: pda_id > 0
      subsidize_affordable: True
      enable_in_scenarios: ["1"]

    capital_gains_tax_settings:
      name: "Capital Gains Tax"
      sending_buildings_subaccount_def: regional
      total_amount: 42000000
      receiving_buildings_filter: pda_id > 0
      subsidize_affordable: True
      enable_in_scenarios: ["1"]

  profitability_adjustment_policies:  

    ceqa_tiering:
      name: "CEQA"
      enable_in_scenarios: ["1", "2", "3", "4"]
      # any parcel in a tpa
      profitability_adjustment_formula: "(tpp_id > 0) * .01"

    parking_requirements_tpps:
      name: "Reduce Parking Requirements in TPPs"
      enable_in_scenarios: ["3"]
      # any parcel in a tpa   
      profitability_adjustment_formula: "(tpp_id > 0) * .01"

    parking_requirements_pdas:
      name: "Reduce Parking Requirements in PDAs"
      enable_in_scenarios: ["1", "2", "4", "5"]
      # any parcel in a tpa
      profitability_adjustment_formula: "(pda_id > 0) * .01"

  land_value_tax_settings:
    enable_in_scenarios: ["3"]
    bins:
      pcts: [0.05, 0.02, 0.01, 0.0]
      breaks: [0.1, 0.3, 0.5]

  sales_tax_settings:
    sending_buildings_filter: general_type != 'Residential'
    # this is the method used to compute the property tax - the 20 here is a cap rate
    # to turn yearly rent into overall value - 1% property tax and 1% actually goes into
    # funding affordable housing
    sending_buildings_tax: non_residential_price * non_residential_sqft * 20 * .01 * .01
    sending_buildings_subaccount_def: city_id
    receiving_buildings_filter: pda_id > 0 and residential_units > 1
  vmt_settings:
    sending_buildings_subaccount_def: regional
    receiving_buildings_filter: pda_id>0
    res_for_res_fee_amounts:
      VH: 25000
      H: 15000
      MH: 5000
    com_for_res_fee_amounts:
      VH: 50
      H: 30
      MH: 20
      M: 3
    com_for_com_fee_amounts:  # commercial fee subsidizing commercial devs
      VH: 40
      H: 20
      MH: 10
  sb743_settings:
    enable: true
    sb743_pcts:
      VH: -0.02
      H: -0.01
      MH: -0.005
      M: 0.0
      S: 0.02


low_income_for_hlcm: 30000


enable_supply_correction:
  price_col: residential_price
  submarket_col: zone_id
  submarket_table: zones
  warm_start: False
  multiplier_func: supply_and_demand_multiplier_func
  clip_final_price_low: null
  clip_final_price_high: null
  kwargs:
    clip_change_low: 1.0
    clip_change_high: 1.2
    iterations: 8


table_reprocess:
  jobs:
    fill_nas:
      empsix:
        how: "mode"
        type: "int"
  buildings:
    fill_nas:
      building_type_id:
        how: "drop"
        type: "int"
      residential_units:
        how: "zero"
        type: "int"
      non_residential_sqft:
        how: "zero"
        type: "int"
      year_built:
        how: "median"
        type: "int"
      building_type_id:
        how: "mode"
        type: "int"


rates:
  households_relocation: .07


build_networks:
  walk:
      name: 2015_06_01_osm_bayarea4326.h5
      max_distance: 3000
  drive:
      name: 2015_08_03_tmnet.h5
      max_distance: 45
      weight_col: "CTIMEA"


households_transition:
  add_columns:
    - base_income_quartile
  total_column: total_number_of_households


jobs_transition:
  add_columns:
    - empsix_id
  total_column: number_of_jobs


rsh_simulate:
  low: 200
  high: 2000



feasibility:
  parcel_filter: nodev != 1 and manual_nodev != 1 and sdem != 1 and oldest_building > 1906 and oldest_building_age > 20  and (total_residential_units != 1 or parcel_acres > 1.0) and first_building_type_id != 5 and first_building_type_id != 6
  residential_to_yearly: True
  simple_zoning: True
  pass_through:
    - oldest_building
    - total_sqft
    - total_residential_units
    - max_far
    - max_dua
    - land_cost
    - residential
    - min_max_fars
    - max_height
    - building_purchase_price
    - building_purchase_price_sqft
    - residential_sales_price_sqft
    - pda
    - juris
    - county
    - superdistrict
    - geom_id
    - vmt_res_cat


residential_developer:
  target_vacancy: .03
  min_unit_size: 1000
  bldg_sqft_per_job: 400
  max_parcel_size: 150000000

non_residential_developer:
  kwargs:
    target_vacancy: 0.05
    bldg_sqft_per_job: 400
  type_splits:
    Industrial: 0.0
    Retail: 0.2
    Office: 0.8

pusher:
  key: 7d78b1b3454b78aed26f
  secret: d87736e21dd7819926e6
  host: http://localhost:8765/
  region: bayarea


store: 2015_09_01_bayarea_v3.h5


scenario: "4"


# this maps Synthicity's 25 employment categories to
# the six major employment categories traditionally
# used by MTC and ABAG for use in output to the Travel Model
naics_to_empsix:
  10: AGREMPN
  11: AGREMPN
  21: AGREMPN
  22: MWTEMPN
  23: OTHEMPN
  31: MWTEMPN
  3133: MWTEMPN
  32: MWTEMPN
  33: MWTEMPN
  42: MWTEMPN
  44: RETEMPN
  4445: RETEMPN
  45: RETEMPN
  48: MWTEMPN
  4849: MWTEMPN
  49: MWTEMPN
  51: OTHEMPN
  52: FPSEMPN
  53: FPSEMPN
  54: FPSEMPN
  55: FPSEMPN
  56: FPSEMPN
  61: HEREMPN
  62: HEREMPN
  71: HEREMPN
  72: HEREMPN
  81: OTHEMPN
  91: OTHEMPN
  92: OTHEMPN
  99: OTHEMPN
  3133: MWTEMPN
  4445: RETEMPN
  4849: MWTEMPN

empsix_name_to_id:
  AGREMPN: 1
  MWTEMPN: 2
  RETEMPN: 3
  FPSEMPN: 4
  HEREMPN: 5
  OTHEMPN: 6


# this maps building type ids to general building types
# basically just reduces dimensionality
building_type_map:
  0: Other
  1: Residential
  2: Residential
  3: Residential
  4: Office
  5: Hotel
  6: School
  7: Industrial
  8: Industrial
  9: Industrial
  10: Retail
  11: Retail
  12: Residential
  13: Retail
  14: Office
  15: Parking
  16: Parking


building_type_map2:
  O: 0
  HS: 1
  HT: 2
  HM: 3
  OF: 4
  HO: 5
  SC: 6
  IL: 7
  IW: 8
  IH: 9
  RS: 10
  RB: 11
  MR: 12
  MT: 13
  ME: 14
  PA: 15
  PA2: 16

# this maps building "forms" from the developer model
# to building types so that when the developer builds a
# "form" this can be converted for storing as a type
# in the building table - in the long run, the developer
# forms and the building types should be the same and the
# developer model should account for the differences.
# travel_model_ variables are for the travel_model_summary step.
form_to_btype:
  residential:
    - 1
    - 2
    - 3
  industrial:
    - 7
    - 8
    - 9
  retail:
    - 10
    - 11
  office:
    - 4
  mixedresidential:
    - 12
  mixedoffice:
    - 14
  select_non_residential:
    - 4
    - 5
    - 6 
    - 7
    - 8
    - 9
    - 10
    - 11
    - 13
    - 14

building_sqft_per_job:
  -1: 400
  0: 400
  1: 400
  2: 400
  3: 400
  4: 355
  5: 1161
  6: 470
  7: 661
  8: 960
  9: 825
  10: 445
  11: 445
  12: 383
  13: 383
  14: 383

county_id_map:
  85: Santa Clara
  1: Alameda
  13: Contra Costa
  81: San Mateo
  97: Sonoma
  75: San Francisco
  95: Solano
  41: Marin
  55: Napa

county_id_tm_map:
  3: Santa Clara
  4: Alameda
  5: Contra Costa
  2: San Mateo
  8: Sonoma
  1: San Francisco
  6: Solano
  9: Marin
  7: Napa

pda_price_shifters:
  "ber1": 1
  "ber2": 1
  "ber3": 1
  "ber4": 1
  "ber5": 1
  "ber6": 1
  "sfo3": 1
  "sfo5": 1
  "sfo11": 1

cost_shifters:
  "Santa Clara": 1.3
  "San Francisco": 0.8
  "San Mateo": 0.8
  "Sonoma": 1.0
  "Solano": 0.75
  "Alameda": 0.7
  "Napa": 0.9
  "Marin": 1.0
  "Contra Costa": 0.75


development_limits:
  default:
    Office:
      'Alameda': 100
      'Atherton': 0
      'Belvedere': 0
      'Belmont': 0
      'Benicia': 25
      'Burlingame': 275
      'Clayton': 0
      'Colma': 0
      'Concord': 1000
      'Cupertino': 0
      'Daly City': 50
      'Fairfax': 0
      'Half Moon Bay': 0
      'Healdsburg': 0
      'Hillsborough': 0
      'Larkspur': 0
      'Los Altos Hills': 0
      'Los Gatos': 0
      'Milpitas': 325
      'Mill Valley': 0
      'Millbrae': 200
      'Monte Sereno': 0
      'Orinda': 0
      'Palo Alto': 175
      'Petaluma': 150
      'Piedmont': 0
      'Pleasanton': 275
      'Portola Valley': 0
      'Redwood City': 550
      'Ross': 0
      'San Anselmo': 0
      'San Francisco': 3500
      'San Mateo': 200
      'San Rafael': 0
      'St. Helena': 5
      'Saratoga': 0
      'Sonoma': 0
      'Tiburon': 0
      'Union City': 5
      'Woodside': 0 
      'Alameda County': 0
      'Contra Costa County': 0
      'Marin County': 0
      'Solano County': 0
      'Sonoma County': 0
    Residential:
      'Cloverdale': 50
      'Fairfax': 8
      'Half Moon Bay': 44
      'Petaluma': 75
      'San Mateo': 400
      'Sebastopol': 10
      'St. Helena': 10
      'Woodside': 5
      'Yountville': 2
      'Alameda County': 205
      'Napa County': 25
      'Solano County': 230
      'Sonoma County': 50
  "2":
    Office:
      'San Francisco': 5250
  "5":
    Office:
      'San Francisco': 5250


zoning_column_dictionary: 
  id: "generic zoning id"
  juris: "jurisdiction id"
  city: "city name"
  name: "string of zoning type from source data"
  max_far: "maximum floor-to-area ratio"
  max_height: "maximum height"
  max_dua: "maximum dwelling units per acre"
  max_du_per_parcel: "maximum dwelling units per parcel"
  hs: "single-family detached"
  ht: "single-family attached"
  hm: "multi-family"
  of: "office"
  ho: "hotel"
  sc: "school"
  il: "light industrial"
  iw: "warehouse industrial"
  ih: "heavy industrial"
  rs: "strip mall retail"
  rb: "big-box retail"
  mr: "residential-focus mixed"
  mt: "retail-focus mixed"
  me: "employment-focus mixed"


static_parcels:
  - 11280465768398 # city hall
  - 2240580234395 # sf state
  - 7299494955245 # sj state
  - 13202883289710 # sj state
  - 6193503633797 # sj state
  - 8603860488630 # sj state
  - 8173572322083 # ucb
  - 14259504015679 # labs
  - 3473860030354 # sfo
  - 11976417381057 # sf general
  - 5600199824880 # more sf gen
  - 9143399820283
  - 2161358104676
  - 15636310238820
  - 14512305680993 # sonoma state
  - 15424804982410 # cal state east bay
  - 7414256675266 # cal state east bay
  - 8817315949318 # san quentin
  - 12668875358422 # san quentin
  
  
  
