# active scenario if not specified on the command line
scenario: "4"


# STORAGE

# location of the hdf store
store: 2015_09_01_bayarea_v3.h5

# large baus files are stored in s3 - this key gives the settings for fetching them
s3_settings:
  bucket: bayarea_urbansim
  files:
    - 2015_09_01_bayarea_v3.h5
    - 2015_06_01_osm_bayarea4326.h5
    - 2015_12_21_zoning_parcels.csv
    - 02_01_2016_parcels_geography.csv
    - 2015_08_29_costar.csv
    - 2015_08_03_tmnet.h5

# some info on where to get the accessibliity networks
build_networks:
  walk:
      name: 2015_06_01_osm_bayarea4326.h5
      max_distance: 3000
  drive:
      name: 2015_08_03_tmnet.h5
      max_distance: 45
      weight_col: "CTIMEA"

# these are the tables the get auto-merged to buildings/parcels in the hedonic and lcms
aggregation_tables:
  - nodes
  - tmnodes
  - logsums
  - buildings


# RELOCATION

# household relocation rates split by rent / own
relocation_rates:
  tenure:
    - 1
    - 2
  probability_of_relocating:
    - 0.15
    - 0.25


# TRANSITION

# inputs to the transition model for households
households_transition:
  add_columns:
    - base_income_quartile
  total_column: total_number_of_households

# info to the transition model for jobs
jobs_transition:
  add_columns:
    - empsix_id
  total_column: number_of_jobs


# DEVELOPER

# cap rate for use in the developer model
cap_rate: 0.04

# settings for the feasibility model - parcel_filter is very important and is a rule of
# which parcels to consider - we don't consider nodev properties, historic properties, and
# optionally we don't look at small lot single family
# pass_through are columns not used by the developer but which go in the debug output
feasibility:
  parcel_filter: (nodev != 1 and manual_nodev != 1 and sdem != 1 and oldest_building > 1906
    and oldest_building_age > 20 and (total_residential_units != 1 or parcel_acres > 1.0)
    and first_building_type != 'HO' and first_building_type != 'SC')
  residential_to_yearly: True
  simple_zoning: True
  pass_through:
    - oldest_building
    - total_sqft
    - total_residential_units
    - max_far
    - max_dua
    - land_cost
    - residential
    - min_max_fars
    - max_height
    - building_purchase_price
    - building_purchase_price_sqft
    - residential_sales_price_sqft
    - pda
    - trich_id
    - cat_id
    - juris
    - county
    - superdistrict
    - geom_id
    - vmt_res_cat
    - vmt_nonres_cat

# settings that get passed to the residential developer as kwargs
residential_developer:
  target_vacancy: .03
  min_unit_size: 1000
  bldg_sqft_per_job: 400
  max_parcel_size: 150000000

# same as above for non-res
non_residential_developer:
  kwargs:
    target_vacancy: .05
    bldg_sqft_per_job: 400
  type_splits:
    Industrial: 0.0
    Retail: 0.2
    Office: 0.8


# BUILDINGS

# jobs sqft per building type
building_sqft_per_job:
  HS: 400
  HT: 400
  HM: 400
  OF: 355
  HO: 1161
  SC: 470
  IL: 661
  IW: 960
  IH: 825
  RS: 445
  RB: 445
  MR: 383
  MT: 383
  ME: 383

# sqft per unit is often bad so we clip it to certain sizes - these are the
# sizes the developer model will be testing
ave_sqft_per_unit_clip:
  lower: 800
  upper: 2500

# we don't have great sqft_per_unit info across the bay area (building data
# is poor on this metric) so we use DUA to get a clue as to sqft per unit
# we assume high DUA areas will yield slightly smaller units
clip_sqft_per_unit_based_on_dua:
  - threshold: 50
    max: 1000
  - threshold: 100
    max: 900
  - threshold: 150
    max: 800


# HEDONIC

# clip the prices that come out of the sales hedonic
rsh_simulate:
  low: 200
  high: 2000


# EQUILIBRATION

# price and rent equilibration, treated separately
price_equilibration:
  price_col: unit_residential_price
  submarket_col: submarket_id
  submarket_table: zones
  warm_start: False
  multiplier_func: supply_and_demand_multiplier_func
  clip_final_price_low: null
  clip_final_price_high: null
  kwargs:
    clip_change_low: 1.0
    clip_change_high: 1.2
    iterations: 8

rent_equilibration:
  price_col: unit_residential_rent
  submarket_col: submarket_id
  submarket_table: zones
  warm_start: False
  multiplier_func: supply_and_demand_multiplier_func
  clip_final_price_low: null
  clip_final_price_high: null
  kwargs:
    clip_change_low: 1.0
    clip_change_high: 1.2
    iterations: 8


# SHIFTERS

# price shisfters per pda - price is multiplied by this amount
pda_price_shifters:
  "ber1": 1
  "ber2": 1
  "ber3": 1
  "ber4": 1
  "ber5": 1
  "ber6": 1
  "sfo3": 1
  "sfo5": 1
  "sfo11": 1

# cost shifters per county - cost is multiplied by this amount
cost_shifters:
  "Santa Clara": 1.3
  "San Francisco": 0.8
  "San Mateo": 0.8
  "Sonoma": 1.0
  "Solano": 0.75
  "Alameda": 0.7
  "Napa": 0.9
  "Marin": 1.0
  "Contra Costa": 0.75


# DISALLOW

# this is really because we don't have limits right now for retail
# we can disallow new retail per city using this list of cities
eliminate_retail_zoning_from_juris:
  - 'Sonoma County'
  - 'Contra Costa County'
  - 'San Mateo County'
  - 'Solano County'
  - 'Napa County'
  - 'Marin County'
  - 'Benicia'
  - 'Brentwood'
  - 'Antioch'
  - 'Atherton'
  - 'Fairfax'
  - 'Hillsborough'
  - 'Belvedere'
  - 'Yountville'
  - 'Woodside'
  - 'Monte Sereno'
  - 'Los Altos Hills'
  - 'Half Moon Bay'
  - 'Larkspur'
  - 'Portola Valley'
  - 'Saratoga'
  - 'Cloverdale'
  - 'Livermore'
  - 'Los Gatos'
  - 'Tiburon'
  - 'Piedmont'
  - 'Ross'
  - 'Atherton'
  - 'Belmont'
  - 'Clayton'

# a list of parcel geom ids which urbansim doesn't touch - this are viewed as exceptions
# and are often dealt with using specific models (SDEM and possibly proportional jobs model)
# which ignore this list
static_parcels:
  - 11280465768398 # city hall
  - 2240580234395 # sf state
  - 7299494955245 # sj state
  - 13202883289710 # sj state
  - 6193503633797 # sj state
  - 8603860488630 # sj state
  - 8173572322083 # ucb
  - 14259504015679 # labs
  - 3473860030354 # sfo
  - 11976417381057 # sf general
  - 5600199824880 # more sf gen
  - 9143399820283
  - 2161358104676
  - 15636310238820
  - 14512305680993 # sonoma state
  - 15424804982410 # cal state east bay
  - 7414256675266 # cal state east bay
  - 8817315949318 # san quentin
  - 12668875358422 # san quentin


# MISCELLANY

# the weight to use to combine profit vs ROC to create a probability.  A 1.0 would mean
# equal weights.  0.5 means profit is half as much as ROC
profit_vs_return_on_cost_combination_factor: 0.5

# a settings to not build the most dense building in any zone, even if zoning allows
# it - reduces zoning to match the most dense building
dont_build_most_dense_building: True

# add residential units if the number of households exceeds the number of units in
# the base year data
reconcile_residential_units_and_households: True

# same as above but for non-res
reconcile_non_residential_sqft_and_jobs: True

# if households or jobs are in building that don't exist, unplace them so they can be
# placed the next time through the LCMs
remove_invalid_building_ids: True

# sets nan to zero so later models can run - usually used when these prices aren't
# used but there is a check to force the models to fail before filters are applied
set_nan_price_to_zero: True

# convert square meters to square feet
parcel_size_factor: 10.764

# towards the end of the process we got a new tpp_id and didn't have the ability to
# quickly turn around a new parcels_geography file to replace the old one
use_new_tpp_id_in_topsheet: True






