aggregation_tables:
  - nodes
  - logsums


unit_aggregation_tables:
  - buildings
  - nodes
  - logsums


set_nan_price_to_zero: True


remove_invalid_building_ids: True


reconcile_residential_units_and_households: False


reconcile_non_residential_sqft_and_jobs: False


set_nan_price_to_zero: True


parcel_size_factor: 10.764


ave_sqft_per_unit_clip:
  lower: 800
  upper: 2500


acct_settings:
  disable: False
  sending_buildings_filter: general_type != 'Residential'
  sending_buildings_tax: non_residential_price * non_residential_sqft * 20 * .01 * .01
  sending_buildings_subaccount_def: city_id
  receiving_buildings_filter: pda_id > 0 and residential_units > 1


dont_enable_supply_correction:
  price_col: unit_residential_price
  submarket_col: zone_id
  submarket_table: zones
  warm_start: False
  multiplier_func: supply_and_demand_multiplier_func
  clip_final_price_low: 200
  clip_final_price_high: 2000
  kwargs:
    clip_change_low: 1.0
    clip_change_high: 1.2
    iterations: 8


table_reprocess:
  jobs:
    fill_nas:
      empsix:
        how: "mode"
        type: "int"
  buildings:
    fill_nas:
      building_type_id:
        how: "drop"
        type: "int"
      residential_units:
        how: "zero"
        type: "int"
      non_residential_sqft:
        how: "zero"
        type: "int"
      year_built:
        how: "median"
        type: "int"
      building_type_id:
        how: "mode"
        type: "int"


rates:
  households_relocation_filtered: 
    renter:
      rate: 0.25
      filter: hownrent == 2
    owner:
      rate: 0.15
      filter: hownrent == 1
  households_relocation: .05
  jobs_relocation: .05
  simple_households_transition: .02
  simple_jobs_transition: .02


build_networks:
  name: 2015_06_01_osm_bayarea4326.h5
  max_distance: 1500


households_transition:
  add_columns:
    - income_quartile
  total_column: total_number_of_households


jobs_transition:
  add_columns:
    - empsix_id
  total_column: number_of_jobs


feasibility:
  parcel_filter: nodev != 1 and oldest_building > 1940 and (total_residential_units != 1 or parcel_acres > .5) 
  residential_to_yearly: False
  pass_through:
    - oldest_building
    - total_sqft
    - max_far
    - max_dua
    - land_cost
    - min_max_fars
    - max_far_from_dua
    - max_height
    - max_far_from_heights
    - building_purchase_price
    - building_purchase_price_sqft
    - pda
    - geom_id


residential_developer:
  target_vacancy: .10
  min_unit_size: 1000
  bldg_sqft_per_job: 400
  max_parcel_size: 150000000

non_residential_developer:
  target_vacancy: .08
  bldg_sqft_per_job: 400


pusher:
  key: 7d78b1b3454b78aed26f
  secret: d87736e21dd7819926e6
  host: http://localhost:8765/
  region: bayarea


store: 2015_06_01_bayarea_v3.h5


scenario: np


scenario_inputs:
  baseline:
    zoning_table_name: zoning_baseline
  np:
    zoning_table_name: zoning_np


# this maps Synthicity's 25 employment categories to
# the six major employment categories traditionally
# used by MTC and ABAG for use in output to the Travel Model
naics_to_empsix:
  11: AGREMPN
  21: AGREMPN
  22: MWTEMPN
  23: OTHEMPN
  31: MWTEMPN
  3133: MWTEMPN
  32: MWTEMPN
  33: MWTEMPN
  42: MWTEMPN
  44: RETEMPN
  4445: RETEMPN
  45: RETEMPN
  48: MWTEMPN
  4849: MWTEMPN
  49: MWTEMPN
  51: OTHEMPN
  52: FPSEMPN
  53: FPSEMPN
  54: FPSEMPN
  55: FPSEMPN
  56: FPSEMPN
  61: HEREMPN
  62: HEREMPN
  71: HEREMPN
  72: HEREMPN
  81: OTHEMPN
  92: OTHEMPN
  99: OTHEMPN
  3133: MWTEMPN
  4445: RETEMPN
  4849: MWTEMPN

empsix_name_to_id:
  AGREMPN: 1
  MWTEMPN: 2
  RETEMPN: 3
  FPSEMPN: 4
  HEREMPN: 5
  OTHEMPN: 6


# this maps building type ids to general building types
# basically just reduces dimensionality
building_type_map:
  0: Other
  1: Residential
  2: Residential
  3: Residential
  4: Office
  5: Hotel
  6: School
  7: Industrial
  8: Industrial
  9: Industrial
  10: Retail
  11: Retail
  12: Residential
  13: Retail
  14: Office
  15: Parking
  16: Parking


building_type_map2:
  O: 0
  HS: 1
  HT: 2
  HM: 3
  OF: 4
  HO: 5
  SC: 6
  IL: 7
  IW: 8
  IH: 9
  RS: 10
  RB: 11
  MR: 12
  MR: 13
  ME: 14
  PA: 15
  PA2: 16

# this maps building "forms" from the developer model
# to building types so that when the developer builds a
# "form" this can be converted for storing as a type
# in the building table - in the long run, the developer
# forms and the building types should be the same and the
# developer model should account for the differences
form_to_btype:
  residential_ownerocc:
    - 1
    - 2
    - 3
  residential_rented:
    - 1
    - 2
    - 3
  industrial:
    - 7
    - 8
    - 9
  retail:
    - 10
    - 11
  office:
    - 4
  mixedresidential_ownerocc:
    - 12
  mixedresidential_rented:
    - 12
  mixedoffice_ownerocc:
    - 14
  mixedoffice_rented:
    - 14


building_sqft_per_job:
  -1: 400
  1: 400
  2: 400
  3: 400
  4: 355
  5: 1161
  6: 470
  7: 661
  8: 960
  9: 825
  10: 445
  11: 445
  12: 383
  13: 383
  14: 383

county_id_map:
  85: Santa Clara
  1: Alameda
  13: Contra Costa
  81: San Mateo
  97: Sonoma
  75: San Francisco
  95: Solano
  41: Marin
  55: Napa

pda_price_shifters:
  "ber1": 1.5
  "ber2": 1.5
  "ber3": 1.5
  "ber4": 1.5
  "ber5": 1.5
  "ber6": 1.5
  "sfo3": 1.25
  "sfo5": 1.25
  "sfo11": 1.25

cost_shifters:
  "Santa Clara": 1.2
  "San Francisco": .8
  "San Mateo": .8
  "Sonoma": 1.0
  "Solano": .75
  "Alameda": .8
  "Napa": .9
  "Marin": 1.0
  "Contra Costa": .75
